apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura
  labels:
    app: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      containers:
        - name: hasura
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescale-timescaledb-passwords
                  key: postgres
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://postgres:$(POSTGRES_PASSWORD)@timescale:5432/postgres
          image: hasura/graphql-engine:v1.0.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hasura
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hasura